# Generated by Django 2.0.3 on 2018-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0003_auto_20180328_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='Classification',
            field=models.CharField(max_length=4),
        ),
    ]
