# Generated by Django 2.0.3 on 2018-03-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Analyzed Url', max_length=300)),
                ('Classification', models.CharField(choices=[('Real', 'Real'), ('Fake', 'Fake')], max_length=4)),
                ('Voting', models.IntegerField()),
            ],
        ),
    ]
