# Generated by Django 2.0.3 on 2018-03-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_auto_20180328_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='Url',
        ),
        migrations.AddField(
            model_name='url',
            name='Text',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='url',
            name='Title',
            field=models.TextField(default='None'),
        ),
    ]
