# Generated by Django 2.0.3 on 2018-03-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0004_auto_20180328_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='Voting',
        ),
        migrations.AddField(
            model_name='url',
            name='Dislikes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='url',
            name='Likes',
            field=models.IntegerField(default='0'),
        ),
    ]
