# Generated by Django 2.0.3 on 2018-03-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0005_auto_20180330_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='Rating',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=3),
        ),
    ]
