# Generated by Django 2.0.2 on 2018-04-03 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fakenews', '0006_url_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Like', models.BooleanField(default='False')),
                ('Dislike', models.BooleanField(default='False')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakenews.Url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='users',
            field=models.ManyToManyField(through='fakenews.Vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('url', 'user')},
        ),
    ]
